# Generated by Django 4.0.4 on 2022-05-28 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('serie', models.CharField(max_length=100)),
                ('contador', models.IntegerField(default=0)),
                ('trabajos', models.TextField()),
                ('tecnico', models.CharField(max_length=100)),
                ('finalizado', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
